name: "Update HTML"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/20 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium Pillow
      - name: Install Japanese font
        run: sudo apt-get install fonts-ipafont
      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@v1.0.5
      - name: Start XVFB
        run: Xvfb :99 &
      - name: Run generateHtml.py
        run: python generateHtml.py
      - name: Run screenshot.py
        run: |
          mkdir -p img
          python screenshot.py
        env:
          DISPLAY: :99
      - name: Run update_ogp.py
        run: |
          python update_ogp.py
        env:
          TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
          TWITTER_PHONE: ${{ secrets.TWITTER_PHONE }}
          DISPLAY: :99
      - name: Update
        run: |
          git add -N index.html
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add index.html img/ogp.png img/graph.png
            git commit -m "Update HTML"
            git push
          fi
